apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: web
  template:
    metadata:
      labels:
        components: web
    spec:
      containers:
      - name: client
        image: chinedunsidinanya/multi-client:v2
        
        ports:
        - containerPort: 3000
