apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: server
  template:
    metadata:
      labels:
        components: server
    spec:
      containers:
      - name: server-contianer
        image: chinedunsidinanya/multi-server:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "800Mi"
            cpu: "800m"
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: '6379'
          - name: PGUSER
            value: postgres
          - name: PGHOST
            value: postgres-cluster-ip-service
          - name: PGPORT
            value: '5432'
          - name: PGDATABASE
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: pgpasswords
